# Generated by Django 4.0.1 on 2022-02-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_userinput_is_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='is_modified',
            field=models.DateTimeField(null=True),
        ),
    ]
