# Generated by Django 4.0.1 on 2022-03-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_userinput_options_userinput_igst_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='invoice_num',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
